<?php

namespace AppBundle\Repository;

/**
 * CommentRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
